#Para escrever comentários ##
############################# Makefile ##########################
output:client server
	
client: 
	gcc -Wall client.c -o client

server:
	gcc -Wall server.c -o server















